
## GOAL - The goal of the workflow is to do the continous intergarion of the project and countinous delivery of the LUMAshop project

name: CD workflow

on: 
  workflow_call:   ## This will use when you want to run the code by yourself using button.

jobs: 
    Building-application-and-Deploying-it:
      runs-on: self-hosted

      steps:
        - name: clone the code
          uses: actions/checkout@v7

        - name: Deploy the application using run docker container
          secrets: inherit
          run: docker compose up -d


